# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 500)
        MainWindow.setStyleSheet("backgroud-color: rgb(45, 45, 45)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("background-color: rgb(41, 44, 53);")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(65, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(33, 37, 42);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menu = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menu.setObjectName("frame_top_menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menu)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.button_service = QtWidgets.QPushButton(self.frame_top_menu)
        self.button_service.setMinimumSize(QtCore.QSize(0, 40))
        self.button_service.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(220, 220, 220);\n"
"    background-color:rgb(33, 37, 42);\n"
"    border: 0xp solid;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(41, 44, 53);\n"
"    border-left: 22px solid qlineargradient(spread:pad, x1:0.034, y1:0, x2:0.216, y2:0, stop:0.499 rgba(255, 121, 198, 255), stop:0.5 rgba(85, 170, 255, 0));\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #566388;\n"
"}")
        self.button_service.setObjectName("button_service")
        self.verticalLayout_4.addWidget(self.button_service)
        self.button_app = QtWidgets.QPushButton(self.frame_top_menu)
        self.button_app.setMinimumSize(QtCore.QSize(0, 40))
        self.button_app.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(220, 220, 220);\n"
"    background-color:rgb(33, 37, 42);\n"
"    border: 0xp solid;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(41, 44, 53);\n"
"    border-left: 22px solid qlineargradient(spread:pad, x1:0.034, y1:0, x2:0.216, y2:0, stop:0.499 rgba(255, 121, 198, 255), stop:0.5 rgba(85, 170, 255, 0));\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #566388;\n"
"}")
        self.button_app.setObjectName("button_app")
        self.verticalLayout_4.addWidget(self.button_app)
        self.button_system = QtWidgets.QPushButton(self.frame_top_menu)
        self.button_system.setMinimumSize(QtCore.QSize(0, 40))
        self.button_system.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(220, 220, 220);\n"
"    background-color:rgb(33, 37, 42);\n"
"    border: 0xp solid;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(41, 44, 53);\n"
"    border-left: 22px solid qlineargradient(spread:pad, x1:0.034, y1:0, x2:0.216, y2:0, stop:0.499 rgba(255, 121, 198, 255), stop:0.5 rgba(85, 170, 255, 0));\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #566388;\n"
"}")
        self.button_system.setObjectName("button_system")
        self.verticalLayout_4.addWidget(self.button_system)
        self.button_info = QtWidgets.QPushButton(self.frame_top_menu)
        self.button_info.setMinimumSize(QtCore.QSize(0, 40))
        self.button_info.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(220, 220, 220);\n"
"    background-color:rgb(33, 37, 42);\n"
"    border: 0xp solid;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(41, 44, 53);\n"
"    border-left: 22px solid qlineargradient(spread:pad, x1:0.034, y1:0, x2:0.216, y2:0, stop:0.499 rgba(255, 121, 198, 255), stop:0.5 rgba(85, 170, 255, 0));\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #566388;\n"
"}")
        self.button_info.setObjectName("button_info")
        self.verticalLayout_4.addWidget(self.button_info)
        self.verticalLayout_3.addWidget(self.frame_top_menu, 0, QtCore.Qt.AlignTop)
        self.button_exit = QtWidgets.QPushButton(self.frame_left_menu)
        self.button_exit.setMinimumSize(QtCore.QSize(0, 40))
        self.button_exit.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(220, 220, 220);\n"
"    background-color:rgb(33, 37, 42);\n"
"    border: 0xp solid;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(41, 44, 53);\n"
"    border-left: 22px solid qlineargradient(spread:pad, x1:0.034, y1:0, x2:0.216, y2:0, stop:0.499 rgba(255, 121, 198, 255), stop:0.5 rgba(85, 170, 255, 0));\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #566388;\n"
"}")
        self.button_exit.setObjectName("button_exit")
        self.verticalLayout_3.addWidget(self.button_exit)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pages = QtWidgets.QStackedWidget(self.frame_pages)
        self.pages.setObjectName("pages")
        self.page_service = QtWidgets.QWidget()
        self.page_service.setAutoFillBackground(False)
        self.page_service.setObjectName("page_service")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_service)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.service_frame = QtWidgets.QFrame(self.page_service)
        self.service_frame.setMinimumSize(QtCore.QSize(0, 150))
        self.service_frame.setStyleSheet("")
        self.service_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.service_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.service_frame.setObjectName("service_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.service_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.service_table = QtWidgets.QTableWidget(self.service_frame)
        self.service_table.setStyleSheet("border: none;\n"
"color: rgb(220, 220, 220);")
        self.service_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.service_table.setShowGrid(False)
        self.service_table.setObjectName("service_table")
        self.service_table.setColumnCount(0)
        self.service_table.setRowCount(0)
        self.service_table.horizontalHeader().setVisible(False)
        self.service_table.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.service_table)
        self.service_button = QtWidgets.QFrame(self.service_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.service_button.sizePolicy().hasHeightForWidth())
        self.service_button.setSizePolicy(sizePolicy)
        self.service_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.service_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.service_button.setObjectName("service_button")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.service_button)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.service_button_on = QtWidgets.QPushButton(self.service_button)
        self.service_button_on.setMinimumSize(QtCore.QSize(0, 40))
        self.service_button_on.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(220, 220, 220);\n"
"    border: 0xp solid;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(41, 44, 53);\n"
"    border-bottom: 5px solid qlineargradient(spread:pad, x1:0, y1:0.0, x2:0, y2:0, stop:0.499 rgba(255, 121, 198, 255), stop:0.5 rgba(85, 170, 255, 0));\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #566388;\n"
"}")
        self.service_button_on.setObjectName("service_button_on")
        self.horizontalLayout_6.addWidget(self.service_button_on)
        self.service_button_off = QtWidgets.QPushButton(self.service_button)
        self.service_button_off.setMinimumSize(QtCore.QSize(0, 40))
        self.service_button_off.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(220, 220, 220);\n"
"    border: 0xp solid;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(41, 44, 53);\n"
"    border-bottom: 5px solid qlineargradient(spread:pad, x1:0, y1:0.0, x2:0, y2:0, stop:0.499 rgba(255, 121, 198, 255), stop:0.5 rgba(85, 170, 255, 0));\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #566388;\n"
"}")
        self.service_button_off.setObjectName("service_button_off")
        self.horizontalLayout_6.addWidget(self.service_button_off)
        self.verticalLayout_2.addWidget(self.service_button)
        self.horizontalLayout_4.addWidget(self.service_frame)
        self.pages.addWidget(self.page_service)
        self.page_app = QtWidgets.QWidget()
        self.page_app.setObjectName("page_app")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.page_app)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.app_frame = QtWidgets.QFrame(self.page_app)
        self.app_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.app_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app_frame.setObjectName("app_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.app_frame)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.app_table = QtWidgets.QTableWidget(self.app_frame)
        self.app_table.setStyleSheet("border: none;\n"
"color: rgb(220, 220, 220);")
        self.app_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.app_table.setShowGrid(False)
        self.app_table.setObjectName("app_table")
        self.app_table.setColumnCount(0)
        self.app_table.setRowCount(0)
        self.app_table.horizontalHeader().setVisible(False)
        self.app_table.verticalHeader().setVisible(False)
        self.verticalLayout_6.addWidget(self.app_table)
        self.app_button = QtWidgets.QFrame(self.app_frame)
        self.app_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.app_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app_button.setObjectName("app_button")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.app_button)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.app_button_on = QtWidgets.QPushButton(self.app_button)
        self.app_button_on.setMinimumSize(QtCore.QSize(0, 40))
        self.app_button_on.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(220, 220, 220);\n"
"    border: 0xp solid;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(41, 44, 53);\n"
"    border-bottom: 5px solid qlineargradient(spread:pad, x1:0, y1:0.0, x2:0, y2:0, stop:0.499 rgba(255, 121, 198, 255), stop:0.5 rgba(85, 170, 255, 0));\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #566388;\n"
"}")
        self.app_button_on.setObjectName("app_button_on")
        self.horizontalLayout_5.addWidget(self.app_button_on)
        self.app_button_off = QtWidgets.QPushButton(self.app_button)
        self.app_button_off.setMinimumSize(QtCore.QSize(0, 40))
        self.app_button_off.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(220, 220, 220);\n"
"    border: 0xp solid;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(41, 44, 53);\n"
"    border-bottom: 5px solid qlineargradient(spread:pad, x1:0, y1:0.0, x2:0, y2:0, stop:0.499 rgba(255, 121, 198, 255), stop:0.5 rgba(85, 170, 255, 0));\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #566388;\n"
"}")
        self.app_button_off.setObjectName("app_button_off")
        self.horizontalLayout_5.addWidget(self.app_button_off)
        self.verticalLayout_6.addWidget(self.app_button)
        self.horizontalLayout.addWidget(self.app_frame)
        self.pages.addWidget(self.page_app)
        self.page_info = QtWidgets.QWidget()
        self.page_info.setObjectName("page_info")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.page_info)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.info_frame = QtWidgets.QFrame(self.page_info)
        self.info_frame.setStyleSheet("border: none;")
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.info_frame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.text_name = QtWidgets.QTextBrowser(self.info_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_name.sizePolicy().hasHeightForWidth())
        self.text_name.setSizePolicy(sizePolicy)
        self.text_name.setMinimumSize(QtCore.QSize(100, 0))
        self.text_name.setStyleSheet("color: rgb(220, 220, 220);")
        self.text_name.setObjectName("text_name")
        self.verticalLayout_8.addWidget(self.text_name)
        self.text_description = QtWidgets.QTextBrowser(self.info_frame)
        self.text_description.setStyleSheet("color: rgb(220, 220, 220);")
        self.text_description.setObjectName("text_description")
        self.verticalLayout_8.addWidget(self.text_description)
        self.horizontalLayout_8.addWidget(self.info_frame)
        self.pages.addWidget(self.page_info)
        self.page_system = QtWidgets.QWidget()
        self.page_system.setObjectName("page_system")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_system)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.system_frame = QtWidgets.QFrame(self.page_system)
        self.system_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.system_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.system_frame.setObjectName("system_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.system_frame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.system_table = QtWidgets.QTableWidget(self.system_frame)
        self.system_table.setStyleSheet("border: none;\n"
"color: rgb(220, 220, 220);")
        self.system_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.system_table.setShowGrid(False)
        self.system_table.setObjectName("system_table")
        self.system_table.setColumnCount(0)
        self.system_table.setRowCount(0)
        self.system_table.horizontalHeader().setVisible(False)
        self.system_table.verticalHeader().setVisible(False)
        self.verticalLayout_7.addWidget(self.system_table)
        self.system_button = QtWidgets.QFrame(self.system_frame)
        self.system_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.system_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.system_button.setObjectName("system_button")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.system_button)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.system_button_on = QtWidgets.QPushButton(self.system_button)
        self.system_button_on.setMinimumSize(QtCore.QSize(0, 40))
        self.system_button_on.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(220, 220, 220);\n"
"    border: 0xp solid;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(41, 44, 53);\n"
"    border-bottom: 5px solid qlineargradient(spread:pad, x1:0, y1:0.0, x2:0, y2:0, stop:0.499 rgba(255, 121, 198, 255), stop:0.5 rgba(85, 170, 255, 0));\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #566388;\n"
"}")
        self.system_button_on.setObjectName("system_button_on")
        self.horizontalLayout_7.addWidget(self.system_button_on)
        self.system_button_off = QtWidgets.QPushButton(self.system_button)
        self.system_button_off.setMinimumSize(QtCore.QSize(0, 40))
        self.system_button_off.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(220, 220, 220);\n"
"    border: 0xp solid;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(41, 44, 53);\n"
"    border-bottom: 5px solid qlineargradient(spread:pad, x1:0, y1:0.0, x2:0, y2:0, stop:0.499 rgba(255, 121, 198, 255), stop:0.5 rgba(85, 170, 255, 0));\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #566388;\n"
"}")
        self.system_button_off.setObjectName("system_button_off")
        self.horizontalLayout_7.addWidget(self.system_button_off)
        self.verticalLayout_7.addWidget(self.system_button)
        self.horizontalLayout_3.addWidget(self.system_frame)
        self.pages.addWidget(self.page_system)
        self.verticalLayout_5.addWidget(self.pages)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_service.setText(_translate("MainWindow", "Service"))
        self.button_app.setText(_translate("MainWindow", "App"))
        self.button_system.setText(_translate("MainWindow", "System"))
        self.button_info.setText(_translate("MainWindow", "Info"))
        self.button_exit.setText(_translate("MainWindow", "Exit"))
        self.service_button_on.setText(_translate("MainWindow", "On"))
        self.service_button_off.setText(_translate("MainWindow", "Off"))
        self.app_button_on.setText(_translate("MainWindow", "On"))
        self.app_button_off.setText(_translate("MainWindow", "Off"))
        self.text_name.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt; font-weight:600;\">Windows 10 Fix</span></p></body></html>"))
        self.text_description.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Программа предназначена для отключения\\удаления ненужного функционала windows 10.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Вкладка Service отвечает за отключение\\включение служб.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Вкладка App отвечает за удаление\\установку приложений Microsoft.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Вкладка System отвечает за изменение системных функций.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Советую не отключать всё безраздумно.</span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Некоторые функции вступят в силу после перезагрузки вашего компьютера.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
#"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Если хотите поддержать разработчика, то вот мой номер счёта:</span></p>\n"
#"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">40817810326002984886</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:16pt;\"><br /></p></body></html>"))
        self.system_button_on.setText(_translate("MainWindow", "On"))
        self.system_button_off.setText(_translate("MainWindow", "Off"))
